{
    'name': 'Hospital Management System',
    'description': """
        Hospital Management System
    """,
    'author': 'Samarpan Trust',
    'website': 'www.samarpan.org',
    'version': "11.0.1.0.0",
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'wizard/charge_wiz_view.xml',
        'wizard/shift_report_wizard.xml',
        'views/hospital_view.xml',
        'views/doctor_view.xml',
        'views/patient_view.xml',
        'views/shift_view.xml',
        'views/ward_view.xml',
        'views/department_view.xml',
        'views/payment_view.xml',
        'views/registration_view.xml',
        'views/resPartner_view.xml',
        'views/demo1_view.xml',
        'views/demo2_view.xml',
        'views/user_view.xml',
        'report/doctor_template.xml',
        'report/doctor_report.xml',
        'report/patient_template.xml',
        'report/patient_report.xml',
        'report/payment_template.xml',
        'report/payment_report.xml',
        'report/shift_template.xml',
        'report/shift_report.xml',
        'report/shift_inherit_template.xml',

    ],
    'installable': True,
    'auto_install': False,
    'application': True,

}
